### ISSUE TITLE
Require review before merging to master

### ISSUE THREAD

**Issue by MatthewHambley** [metomi/fab#17]
In order to protect the master branch from unreviewed code we should turn on the protection features which GitHub provides.

Initially we will require the following for a merge to master:

* Successful completion of all continuous integration runs
* Review by at least one developer
* Discard previous approval on request or branch update
* Branch must be up-to-date before merger

**Comment by stevewardle** [comment]
I agree, for now I've created a rule which turns on all 4 of these
