### ISSUE TITLE
Decide on master merge policy

### ISSUE THREAD

**Issue by MatthewHambley** [metomi/fab#18]
There are two approaches to merging to master.

Either the branch is collapsed to a single change or each commit on the branch is recreated on master.

We should decide on one or the other and enforce it.

**Comment by MatthewHambley** [comment]
I prefer the single commit per branch method. I'm not interested on seeing the development path for the change on trunk. It can be a lot of commits, few of which have any historical value.

**Comment by stevewardle** [comment]
I agree to single commit per branch (I think we may not have stuck to this so far but we should do so now)... I _think_ the rules in the settings have an ability to enforce this as well

**Comment by MatthewHambley** [comment]
This has been activated under `Settings->Options->Merge Button`.
