### ISSUE TITLE
ifort build all

### ISSUE THREAD

**Issue by bblay** [metomi/fab#189]
Finishing touch: I think we just need to find the type specification for ifort, like the ones we have for gfrotran, to avoid the type mismatch errors. I think this will let us build UM and LFRic ATM with ifort.

This is really an issue with the nightly run configs, not Fab itself.

done:
 - replaced the hard-coded gfortran -J flag
 - both gfortran and ifort are tested regularly in #160

**Comment by bblay** [comment]
Got UM building but will probably need assistance from an LFRic expert to configure a build for ATM.

**Comment by MatthewHambley** [comment]
I presume this is obsolete now since there have been IFort builds.
