### ISSUE TITLE
Make sure a suitable set of tools/methods exist to query the tables in the database

### ISSUE THREAD

**Issue by stevewardle** [metomi/fab#28]
As long as the database is maintained using the SQLite DBMS it will always be possible to use the command-line tool associated with that library to interrogate the database. This ticket is concerned with providing a simple tool to allow developers not familiar with SQL to explore the data contained therein.
Views which should be available through the tool are:
  * A list of files and attendant information
    * Hash
    * Contained program units
  * Program unit dependency

While it would nice for this to be presented through a GUI a well implemented terminal interface would suffice.
It is also concerned with the APIs associated with database access. It is not unreasonable for some levels of the API to expose SQL but there should also be higher level methods which do not.

**Comment by matthewrmshin** [comment]
(There are plenty of off-the-shelves SQLite browsing tools available. Search for `sqlite browser`.)

**Comment by MatthewHambley** [comment]
> (There are plenty of off-the-shelves SQLite browsing tools available. Search for `sqlite browser`.)

That's a good suggestion but I suspect we are looking for something more than simply inspecting the content of the tables. I think we need something which embodies pre-written queries as well. What do others think?

**Comment by stevewardle** [comment]
That's kind of what I was thinking... like I can picture a scenario where Fab is doing something unexpected - maybe it's falling over because something it thinks is compiled actually hasn't been - and so I want to check quickly whether the database contains the dependency that should have caused the missing thing to be compiled... Being able to dump out the contents in various ways would be helpful for this kind of thing (I'm not sure if that's what an off-the-shelf tool gives you or not)

**Comment by matthewrmshin** [comment]
Make sense. There are multiple ways to do this. You can write SQL files to do this or Python utilities to do this.

**Comment by MatthewHambley** [comment]
With the completion of #39 and #57 I consider this initial ticket complete. There will be further work as additional features are added.
